export enum VideoActionEnum {
    TOGGLE_PLAY = 'TOGGLE_PLAY',
    RANGE_UPDATED = 'RANGE_UPDATED',
    SKIP_BUTTON_CLICKED = "SKIP_BUTTON_CLICKED",
    PROGESS_BAR_CLICKED = "PROGRESS_BAR_CLICKED",
    PROGRESS_BAR_DRAGGED = "PROGRESS_BAR_DRAGGED",
}
